Traceback (most recent call last):
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/envs/engr131/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# This line of code defines a function
# DO NOT CHANGE THIS LINE OF CODE
def question_5(*args, printing=True):
   
   ...
   
   # This line of code allows us to modify your variable so we can test you did not hard code the problem
   # DO NOT CHANGE THIS CODE
   if args:
      course += args[0]
   
   # This is an if statement that controls if the output is printed
   # DO NOT CHANGE THIS LINE OF CODE
   if printing:
      
      # your print statement, make sure it is at this indentation level
      ...



   # This line of code returns variables
   # DO NOT CHANGE THIS LINE OF CODE
   return course

# This line of code calls the function
# DO NOT CHANGE THIS LINE OF CODE
output = question_5()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[12], line 27[0m
[1;32m     23[0m    [38;5;28;01mreturn[39;00m course
[1;32m     25[0m [38;5;66;03m# This line of code calls the function[39;00m
[1;32m     26[0m [38;5;66;03m# DO NOT CHANGE THIS LINE OF CODE[39;00m
[0;32m---> 27[0m output [38;5;241m=[39m [43mquestion_5[49m[43m([49m[43m)[49m

Cell [0;32mIn[12], line 23[0m, in [0;36mquestion_5[0;34m(printing, *args)[0m
[1;32m     17[0m    [38;5;241m.[39m[38;5;241m.[39m[38;5;241m.[39m
[1;32m     21[0m [38;5;66;03m# This line of code returns variables[39;00m
[1;32m     22[0m [38;5;66;03m# DO NOT CHANGE THIS LINE OF CODE[39;00m
[0;32m---> 23[0m [38;5;28;01mreturn[39;00m [43mcourse[49m

[0;31mUnboundLocalError[0m: local variable 'course' referenced before assignment

